###
GET http://localhost:5000/api/books
content-type: application/json

###
POST http://localhost:5000/api/users/signup
content-type: application/json

{
    "username":"director",
    "password":"director",
    "firstname":"Admin ",
    "lastname":"1",
    "roll":"0000000001",
    "email": "admin@gmail.com"
}